package com.smd.gctcore.common.mixin.whimcraft;

import com.xinyihl.whimcraft.common.integration.adapter.tc6.AdapterTC6InfusionMatrixResearch;
import github.kasuminova.mmce.common.itemtype.ChancedIngredientStack;
import hellfirepvp.modularmachinery.common.crafting.MachineRecipe;
import hellfirepvp.modularmachinery.common.crafting.helper.ComponentRequirement;
import hellfirepvp.modularmachinery.common.crafting.requirement.RequirementIngredientArray;
import net.minecraft.item.ItemStack;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.Collection;

/**
 * Makes the item inputs generated by WhimCraft's research-aware infusion
 * adapter match the NBT present on the original Thaumcraft ingredients.
 *
 * <p>{@link ChancedIngredientStack} stores its NBT matcher separately from
 * its display/input {@link ItemStack}. WhimCraft only fills the latter, while
 * MMCE's {@link RequirementIngredientArray} passes the separate (null) matcher
 * to its inventory lookup. As a result, all Thaumcraft essentia crystals have
 * been treated as interchangeable even though their {@code Aspects} NBT is
 * different.</p>
 */
@Mixin(value = AdapterTC6InfusionMatrixResearch.class, remap = false)
public abstract class MixinAdapterTC6InfusionMatrixResearchNBT {

    @Inject(
            method = "createRecipesFor",
            at = @At("RETURN"),
            remap = false,
            require = 1
    )
    private void gctcore$copyIngredientNBTMatchers(
            CallbackInfoReturnable<Collection<MachineRecipe>> cir
    ) {
        Collection<MachineRecipe> recipes = cir.getReturnValue();
        if (recipes == null) {
            return;
        }

        for (MachineRecipe recipe : recipes) {
            if (recipe == null) {
                continue;
            }
            for (ComponentRequirement<?, ?> requirement : recipe.getCraftingRequirements()) {
                if (!(requirement instanceof RequirementIngredientArray)) {
                    continue;
                }
                for (ChancedIngredientStack ingredient :
                        ((RequirementIngredientArray) requirement).getIngredients()) {
                    ItemStack stack = ingredient.itemStack;
                    if (ingredient.tag == null && stack != null && stack.hasTagCompound()) {
                        ingredient.tag = stack.getTagCompound().copy();
                    }
                }
            }
        }
    }
}
